export const anteojosArray = [
  {
    id: 1,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/59vPKXJ.jpeg",
  },
  {
    id: 2,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/oXXFu4I.jpeg",
  },
  {
    id: 3,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/kDpFrTY.jpeg",
  },
  {
    id: 4,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/aQzIuAb.jpeg",
  },
  {
    id: 5,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/Yo0Qmne.jpeg",
  },
  {
    id: 6,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/enDp5J2.jpeg",
  },
  {
    id: 7,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/mSewlJT.jpeg",
  },
  {
    id: 8,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/KW0tgij.jpeg",
  },
  {
    id: 9,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/14AFcAX.jpeg",
  },
  {
    id: 10,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/Nqr2BqO.jpeg",
  },
  {
    id: 11,
    name: "lentes de sol",
    description: "Plastico",
    size: "Chico",
    image: "https://i.imgur.com/9THuja9.jpeg",
  },
  {
    id: 12,
    name: "lentes de sol",
    description: "Plastico",
    size: "Chico",
    image: "https://i.imgur.com/PbWTS25.jpeg",
  },
  {
    id: 13,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/zsxTGDe.jpeg",
  },
  {
    id: 14,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/hCNYXRK.jpeg",
  },
  {
    id: 15,
    name: "lentes de sol",
    description: "Plastico",
    size: "Chico",
    image: "https://i.imgur.com/jJF93Hl.jpeg",
  },
  {
    id: 16,
    name: "lentes de sol",
    description: "Plastico",
    size: "Chico",
    image: "https://i.imgur.com/l4TLL35.jpeg",
  },
  {
    id: 17,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/7hymMbe.jpeg",
  },
  {
    id: 18,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/ZRPUVJV.jpeg",
  },
  {
    id: 19,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/OBFeHWy.jpeg",
  },
  {
    id: 20,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/4ge0bkC.jpeg",
  },
  {
    id: 21,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/eY6ojmL.jpeg",
  },
  {
    id: 22,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/QjRCAPQ.jpeg",
  },
  {
    id: 23,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/CTSpotR.jpeg",
  },
  {
    id: 24,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/izeCICq.jpeg",
  },
  {
    id: 25,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/XNkedT0.jpeg",
  },
  {
    id: 26,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/ob3oq4Y.jpeg",
  },
  {
    id: 27,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/eZF1qIG.jpeg",
  },
  {
    id: 28,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/iTwJuQi.jpeg",
  },
  {
    id: 29,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/Tg6okzo.jpeg",
  },
  {
    id: 30,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/yYD9H9Z.jpeg",
  },
  {
    id: 31,
    name: "lentes de sol",
    description: "Plastico",
    size: "Chico",
    image: "https://i.imgur.com/wh1XU8c.jpeg",
  },
  {
    id: 32,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/ZRx6a6l.jpeg",
  },
  {
    id: 33,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/Gw9VGZx.jpeg",
  },
  {
    id: 34,
    name: "lentes de sol",
    description: "Plastico",
    size: "Grande",
    image: "https://i.imgur.com/HKCd3qD.jpeg",
  },
  {
    id: 35,
    name: "lentes de sol",
    description: "Plastico",
    size: "Chico",
    image: "https://i.imgur.com/ctAWGml.jpeg",
  },
];
