export const cascadasArray = [
  {
    id: 1,
    name: "Cascada Piedras",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/QOU4CM7.jpeg",
  },
  {
    id: 2,
    name: "Cascada Piedras",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/fI1Hudk.jpeg",
  },
  {
    id: 3,
    name: "Cascada Piedras",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/Zj7Gf1Q.jpeg",
  },
  {
    id: 4,
    name: " Buda en cascada",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/gQeKAfr.jpeg",
  },
  {
    id: 5,
    name: "Cascada Dragon",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/Y4gAaKZ.jpeg",
  },
  {
    id: 6,
    name: "Cascada Flor de Loto",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/o9ocPGJ.jpeg",
  },
  {
    id: 7,
    name: "Cascada Ganesh",
    size: "Grande",
    description: "Yeso pintado.",
    image: "https://i.imgur.com/Bky0GD4.jpeg",
  },
  {
    id: 8,
    name: "Cascada Coral",
    size: "Grande",
    description: "Yeso pintado.",
    image: "https://i.imgur.com/uxz6ICl.jpeg",
  },
  {
    id: 9,
    name: "Cascada Buda",
    size: "Grande",
    description: "Yeso pintado.",
    image: "https://i.imgur.com/Sj8peLe.jpeg",
  },
  {
    id: 10,
    name: "Cascada Ganesh Chico",
    description: "Yeso pintado.",
    size: "Pequeño",
    image: "https://i.imgur.com/LsxXbmb.jpeg",
  },
  {
    id: 11,
    name: "Cascada Elefante",
    size: "Mediano",
    description: "Yeso pintado.",
    image: "https://i.imgur.com/erHqBmy.jpeg",
  },
  {
    id: 12,
    name: "Cascada ",
    size: "Pequeño",
    description: "Yeso pintado.",
    image: "https://i.imgur.com/AWXyJc5.jpeg",
  },
  {
    id: 13,
    name: "Cascada Ganesh Grande",
    size: "Grande",
    description: "Yeso pintado.",
    image: "https://i.imgur.com/Cj1wws7.jpeg",
  },
  {
    id: 14,
    name: "Cascada Ganesh Mediana",
    description: "Yeso pintado.",
    size: "Grande",
    image: "https://i.imgur.com/noiEpz2.jpeg",
  },
  {
    id: 15,
    name: "Cascada Petalos",
    description: "Yeso pintado.",
    size: "Pequeño",
    image: "https://i.imgur.com/kGw9qSi.jpeg",
  },
  {
    id: 16,
    name: "Cascada Hojas",
    description: "Yeso pintado.",
    size: "Pequeño",
    image: "https://i.imgur.com/uJKvnqE.jpeg",
  },
];
