export const cascadasArray = [
  {
    id: 1,
    name: "Cascada Piedras",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/fI1Hudk.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Dragon",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/Y4gAaKZ.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Flor de Loto",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/o9ocPGJ.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Ganesh",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/Bky0GD4.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Coral",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/uxz6ICl.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Buda",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/Sj8peLe.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Ganesh Chico",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/LsxXbmb.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Elefante",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/erHqBmy.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada ",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/AWXyJc5.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Ganesh Grande",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/Cj1wws7.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Ganesh Mediana",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/noiEpz2.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cascada Petalos",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "https://i.imgur.com/kGw9qSi.jpeg",
    labelButton: "Pedir",
    link: "",
  },
];
