export const cascadasArray = [
  {
    id: 1,
    name: "Cascada 1",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "/assets/cascada.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Cascada 2",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "/assets/cascada.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Cascada 3",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "/assets/cascada.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Cascada 4",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "/assets/cascada.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Cascada 4",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "/assets/cascada.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Cascada 4",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "/assets/cascada.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Cascada 4",
    description: "Cascadas pintadas a mano con materiales de alta calidad",
    image: "/assets/cascada.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
];
