export const duendesArray = [
  {
    id: 1,
    name: "Duende ",
    description: "Tamaño: ",
    image: "https://i.imgur.com/ay8d04Z.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 2,
    name: "Duende Bastón de Corazón",
    description: "Tamaño: Chico",
    image: "https://i.imgur.com/7fsk1eh.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 3,
    name: "Duende Corazón",
    description: "Tamaño: Grande",
    image: "https://i.imgur.com/pNW7rcR.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 4,
    name: "Duende Colgante",
    description: "Tamaño: Grande",
    image: "https://i.imgur.com/uLymUmb.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 5,
    name: "Duende Guiño",
    description: "Tamaño: Grande",
    image: "https://i.imgur.com/dzQiJ45.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 6,
    name: "Duende Colgante",
    description: "Tamaño: Chico",
    image: "https://i.imgur.com/gaEUbDi.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 7,
    name: "Duende ",
    description: "Tamaño: Chico. Cabello: Gris",
    image: "https://i.imgur.com/0sWn3jy.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 8,
    name: "Duende Viejita Dulcera",
    description: "Tamaño: Chico",
    image: "https://i.imgur.com/jpD6FTw.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 9,
    name: "Duende Rastas Om",
    description: "Tamaño: Chico",
    image: "https://i.imgur.com/ttfmlxL.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 10,
    name: "Duende ",
    description: "Tamaño: ",
    image: "https://i.imgur.com/h19ydVb.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 11,
    name: "Duende Niña Matera",
    description: "Tamaño: Chica. Cabello: Rosa",
    image: "https://i.imgur.com/Tr973J1.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 12,
    name: "Duende Niña",
    description: "Tamaño: Chico. Cabello: Violeta",
    image: "https://i.imgur.com/1boeN2e.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 13,
    name: "Duende Abundancia",
    description: "Tamaño: Chico",
    image: "https://i.imgur.com/EfClC6M.jpeg",
    labelButton: "Pedir",
    link: "",
  },
];
