export const duendesArray = [
  {
    id: 1,
    name: "Duende",
    description: "Porcelana fria ",
    size: "Pequeño",
    image: "https://i.imgur.com/ay8d04Z.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 2,
    name: "Duende Bastón de Corazón",
    description: "porcelana fria ",
    size: "Pequeño",
    image: "https://i.imgur.com/7fsk1eh.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 3,
    name: "Duende Corazón",
    description: "Porcelana fria ",
    size: "Grande",
    image: "https://i.imgur.com/pNW7rcR.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 4,
    name: "Duende Colgante",
    description: "Porcelana fria ",
    size: "Grande",
    image: "https://i.imgur.com/uLymUmb.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 5,
    name: "Duende Guiño",
    description: "Porcelana fria ",
    size: "Grande",
    image: "https://i.imgur.com/dzQiJ45.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 6,
    name: "Duende Colgante",
    description: "porcelana fria ",
    image: "https://i.imgur.com/gaEUbDi.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 7,
    name: "Duende Cabello Gris",
    description: "porcelana fria ",
    size: "Pequeño",
    image: "https://i.imgur.com/0sWn3jy.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 8,
    name: "Duende Viejita Dulcera",
    description: "porcelana fria ",
    image: "https://i.imgur.com/jpD6FTw.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 9,
    name: "Duende Rastas Om",
    description: "porcelana fria ",
    image: "https://i.imgur.com/ttfmlxL.jpeg",
    size: "Pequeño",

    labelButton: "Pedir",
    link: "",
  },
  {
    id: 10,
    name: "Duende ",
    description: "porcelana fria ",
    image: "https://i.imgur.com/h19ydVb.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 11,
    name: "Duende Niña Matera",
    description: "porcelana fria ",
    image: "https://i.imgur.com/Tr973J1.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 12,
    name: "Duende Niña",
    description: "porcelana fria ",
    image: "https://i.imgur.com/1boeN2e.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 13,
    name: "Duende Abundancia",
    description: "porcelana fria ",
    image: "https://i.imgur.com/EfClC6M.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 14,
    name: "Duende Bebe",
    description: "porcelana fria ",
    image: "https://i.imgur.com/vWzaWC9.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 15,
    name: "Duende Bebe",
    description: "porcelana fria ",
    image: "https://i.imgur.com/zOlZM6T.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 16,
    name: "Duende Bebe",
    description: "porcelana fria ",
    image: "https://i.imgur.com/LQtLUXv.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 17,
    name: "Duende Bebe",
    description: "porcelana fria ",
    image: "https://i.imgur.com/ePtCrkh.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 18,
    name: "Duende Bebe",
    description: "porcelana fria ",
    image: "https://i.imgur.com/z2ZD7ko.jpeg",
    size: "Pequeño",
    labelButton: "Pedir",
    link: "",
  },
];
