export const lamparaSalArray = [
  {
    id: 1,
    name: "Lampara Sal 1",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/lamparasal.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Lampara Sal 2",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/lamparasal.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Lampara Sal 3",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/lamparasal.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Lampara Sal 4",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/lamparasal.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Lampara Sal 5",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/lamparasal.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Lampara Sal 6",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/lamparasal.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Lampara Sal 7",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/lamparasal.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
];
