export const paloSantoArray = [
  {
    id: 1,
    name: "Palo Santo 1",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/palosanto.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Palo Santo 2",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/palosanto.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Palo Santo 3",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/palosanto.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Palo Santo 4",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/palosanto.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Palo Santo 5",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/palosanto.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Palo Santo 6",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/palosanto.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Palo Santo 7",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/palosanto.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
];
