export const portaSahumeriosArray = [
  {
    id: 1,
    name: "Porta Sahumerios Buda",
    description: "Tamaño: Grande",
    image: "https://i.imgur.com/6mopXDU.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Porta Sahumerios Buda",
    description: "Tamaño: Grande",
    image: "https://i.imgur.com/pqpSXR9.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Porta Sahumerios Buda",
    description: "Tamaño: Grande",
    image: "https://i.imgur.com/8zOzLah.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Porta Sahumerios Elefante",
    description: "Tamaño: Mediano",
    image: "https://i.imgur.com/0UYzZ1N.jpeg",
    labelButton: "Pedir",
    link: "",
  },

  {
    id: 1,
    name: "Porta Sahumerios Buda",
    description: "Tamaño: Mediano",
    image: "https://i.imgur.com/7BmMPvR.jpeg",
    labelButton: "Pedir",
    link: "",
  },

  {
    id: 1,
    name: "Porta Sahumerios Buda",
    description: "Tamaño: Mediano",
    image: "https://i.imgur.com/2mZQhXa.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Porta Sahumerios Buda",
    description: "Tamaño: Pequeño",
    image: "https://i.imgur.com/VIGehUe.jpeg",
    labelButton: "Pedir",
    link: "",
  },

  {
    id: 1,
    name: "Porta Sahumerios Elefante",
    description: "Tamaño: Pequeño",
    image: "https://i.imgur.com/ZxW1GLL.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Porta Sahumerios Fribofacil",
    description: "Descripcion: Con imagenes",
    image: "https://i.imgur.com/Ruja7W3.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Porta Sahumerios Fribofacil",
    description: "Descripcion: Calados",
    image: "https://i.imgur.com/sZm4KfK.jpeg",
    labelButton: "Pedir",
    link: "",
  },
];
