export const portaSahumeriosArray = [
  {
    id: 1,
    name: "Porta Sahumerio 1",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/portasahumerios.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Porta Sahumerio 2",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/portasahumerios.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Porta Sahumerio 3",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/portasahumerios.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Porta Sahumerio 4",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/portasahumerios.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Porta Sahumerio 5",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/portasahumerios.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Porta Sahumerio 6",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/portasahumerios.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Porta Sahumerio 7",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/portasahumerios.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
];
