export const portaSahumeriosArray = [
  {
    id: 1,
    name: "Porta Sahumerios ",
    description: "Yeso pintado.",
    size: "Grande",
    image: "https://i.imgur.com/6mopXDU.jpeg",
  },
  {
    id: 2,
    name: "Porta Sahumerios ",
    description: "Yeso pintado.",
    size: "Grande",
    image: "https://i.imgur.com/pqpSXR9.jpeg",
  },
  {
    id: 3,
    name: "Porta Sahumerios ",
    description: "Yeso pintado.",
    size: "Grande",
    image: "https://i.imgur.com/8zOzLah.jpeg",
  },
  {
    id: 4,
    name: "Porta Sahumerios ",
    description: "Yeso pintado.",
    size: "Grande",
    image: "https://i.imgur.com/bzXCEPw.jpeg",
  },
  {
    id: 5,
    name: "Porta Sahumerios ",
    description: "Yeso pintado.",
    size: "Grande",
    image: "https://i.imgur.com/RAQcET4.jpeg",
  },
  {
    id: 6,
    name: "Porta Sahumerios ",
    description: "Yeso pintado.",
    size: "Grande",
    image: "https://i.imgur.com/5dRqtiZ.jpeg",
  },
  {
    id: 7,
    name: "Porta Sahumerios ",
    description: "Yeso pintado.",
    size: "Grande",
    image: "https://i.imgur.com/i1mZt2k.jpeg",
  },
  {
    id: 8,
    name: "Porta Sahumerios Elefante",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/0UYzZ1N.jpeg",
  },
  {
    id: 9,
    name: "Porta Sahumerios Elefante",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/nWgXom1.jpeg",
  },
  {
    id: 10,
    name: "Porta Sahumerios ",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/7BmMPvR.jpeg",
  },

  {
    id: 11,
    name: "Porta Sahumerios Buda",
    description: "Yeso pintado.",
    size: "Mediano",
    image: "https://i.imgur.com/2mZQhXa.jpeg",
  },
  {
    id: 12,
    name: "Porta Sahumerios Buda",
    description: "Yeso pintado.",
    size: "Pequeño",
    image: "https://i.imgur.com/VIGehUe.jpeg",
  },
  {
    id: 13,
    name: "Porta Sahumerios Buda",
    description: "Yeso pintado.",
    size: "Pequeño",
    image: "https://i.imgur.com/TcKznBO.jpeg",
  },
  {
    id: 14,
    name: "Porta Sahumerios Buda",
    description: "Yeso pintado.",
    size: "Pequeño",
    image: "https://i.imgur.com/GD5qJXR.jpeg",
  },

  {
    id: 15,
    name: "Porta Sahumerios Elefante",
    description: "Yeso pintado.",
    size: "Pequeño",
    image: "https://i.imgur.com/ZxW1GLL.jpeg",
  },

  {
    id: 16,
    name: "Porta Sahumerios ",
    description: "Fribofacil.",
    size: "Pequeño",
    image: "https://i.imgur.com/Ruja7W3.jpeg",
  },
  {
    id: 17,
    name: "Porta Sahumerios ",
    description: "Fribofacil.",
    size: "Pequeño",
    image: "https://i.imgur.com/sZm4KfK.jpeg",
  },
  {
    id: 18,
    name: "Porta Sahumerios ",
    description: "Fribofacil.",
    size: "Pequeño",
    image: "https://i.imgur.com/6Etl1pH.jpeg",
  },
  {
    id: 19,
    name: "Porta Sahumerios",
    description: "Fribofacil.",
    size: "Pequeño",
    image: "https://i.imgur.com/fuLxUlq.jpeg",
  },
  {
    id: 20,
    name: "Porta Sahumerios ",
    description: "Fribofacil.",
    size: "Pequeño",
    image: "https://i.imgur.com/sXnAed8.jpeg",
  },
];
