export const sahumadosArray = [
  {
    id: 1,
    name: "Sahumerios",
    description: "Triple empaste, y con una fragancia duradera",
    image: "https://i.imgur.com/B4ziSkr.jpeg",
    size: "Sin especificar",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Bombas de defumación activa",
    description: "Sin especificar",
    image: "https://i.imgur.com/JSy6eQA.jpeg",
    size: "Sin especificar",
    labelButton: "Pedir",
    link: "",
  },
  // {
  //   id: 1,
  //   name: "Sahumos",
  //   description: "Sahumerios de triple empaste, y con una fragancia duradera",
  //   image: "",
  //   labelButton: "Pedir",
  //   link: "",
  // },
  {
    id: 1,
    name: "Conitos",
    description: "Sin especificar",
    image: "https://i.imgur.com/SvGuLcA.jpeg",
    labelButton: "Pedir",
    size: "Sin especificar",

    link: "",
  },
  {
    id: 1,
    name: "Palo Santo",
    description: "Bursera graveolens",
    image: "https://i.imgur.com/gSJg3Oi.jpeg",
    size: "Sin especificar",

    labelButton: "Pedir",
    link: "",
  },
  {
    id: 1,
    name: "Cazuelas",
    description: "Yeso pintado",
    image: "https://i.imgur.com/C8Aws7F.jpeg",
    size: "Sin especificar",
    labelButton: "Pedir",
    link: "",
  },
  // {
  //   id: 1,
  //   name: "Carbon Vegetal",
  //   description: "Sahumerios de triple empaste, y con una fragancia duradera",
  //   image: "",
  //   labelButton: "Pedir",
  //   link: "",
  // },
];
