export const sahumeriosArray = [
  {
    id: 1,
    name: "Sahumerio 1",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/sahumerio.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Sahumerio 2",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/sahumerio.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Sahumerio 3",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/sahumerio.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Sahumerio 4",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/sahumerio.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Sahumerio 4",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/sahumerio.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Sahumerio 4",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/sahumerio.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
  {
    id: 1,
    name: "Sahumerio 4",
    description: "Sahumerios de triple empaste, y con una fragancia duradera",
    image: "/assets/sahumerio.jpg",
    labelButton: "Pedir",
    link: "",
    price: 500,
  },
];
