export const tejidosArray = [
  {
    id: 1,
    name: "Atrapasueños de Mesa",
    description: "Tamaño: Grande",
    image: "https://i.imgur.com/9QHV38o.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 2,
    name: "Atrapasueños Grande",
    description: "Tamaño: Grande",
    image: "https://i.imgur.com/sp5LZIy.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 3,
    name: "Atrapasueños",
    description: "Tamaño: Chico",
    image: "https://i.imgur.com/sdRzo9C.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 4,
    name: "Atrapasueños",
    description: "Tamaño: Chico",
    image: "https://i.imgur.com/R9IuwLm.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 5,
    name: "Atrapasueños",
    description: "Tamaño: Chico",
    image: "https://i.imgur.com/FW5cb91.jpeg",
    labelButton: "Pedir",
    link: "",
  },
  {
    id: 6,
    name: "Atrapasueños",
    description: "Tamaño: Chico",
    image: "https://i.imgur.com/TP0kbS0.jpeg",
    labelButton: "Pedir",
    link: "",
  },
];
